config/routes.rb
Rails.application.routes.draw do
  resources :teams

  resources :mbrackets

end

app/models/mbracket.rb
class Mbracket < ActiveRecord::Base
  has_many :teams

  def to_s
    name
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :mbracket

  def to_s
    name
  end
  def self.ranked(r)
     Team.find_by(:rank => r)
  end

  scope :rank1,  -> {find_by rank:  '1'}
  scope :rank2,  -> {find_by rank:  '2'}
  scope :rank3,  -> {find_by rank:  '3'}
  scope :rank4,  -> {find_by rank:  '4'}
  scope :rank5,  -> {find_by rank:  '5'}
  scope :rank6,  -> {find_by rank:  '6'}
  scope :rank7,  -> {find_by rank:  '7'}
  scope :rank8,  -> {find_by rank:  '8'}
  scope :rank9,  -> {find_by rank:  '9'}
  scope :rank10, -> {find_by rank: '10'}
  scope :rank11, -> {find_by rank: '11'}
  scope :rank12, -> {find_by rank: '12'}
  scope :rank13, -> {find_by rank: '13'}
  scope :rank14, -> {find_by rank: '14'}
  scope :rank15, -> {find_by rank: '15'}
  scope :rank16, -> {find_by rank: '16'}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mbrackets_controller.rb
class MbracketsController < ApplicationController
  before_action :set_mbracket, only: [:show, :edit, :update, :destroy]

  # GET /mbrackets
  # GET /mbrackets.json
  def index
    @mbrackets = Mbracket.all
  end

  # GET /mbrackets/1
  # GET /mbrackets/1.json
  def show
    @team   = Team.all
    @rank1  = Team.rank1
    @rank2  = Team.rank2
    @rank3  = Team.rank3
    @rank4  = Team.rank4
    @rank5  = Team.rank5
    @rank6  = Team.rank6
    @rank7  = Team.rank7
    @rank8  = Team.rank8
    @rank9  = Team.rank9
    @rank10 = Team.rank10
    @rank11 = Team.rank11
    @rank12 = Team.rank12
    @rank13 = Team.rank13
    @rank14 = Team.rank14
    @rank15 = Team.rank15
    @rank16 = Team.rank16
  end


  # GET /mbrackets/new
  def new
    @mbracket = Mbracket.new
  end

  # GET /mbrackets/1/edit
  def edit
  end

  # POST /mbrackets
  # POST /mbrackets.json
  def create
    @mbracket = Mbracket.new(mbracket_params)

    respond_to do |format|
      if @mbracket.save
        format.html { redirect_to @mbracket, notice: 'Mbracket was successfully created.' }
        format.json { render :show, status: :created, location: @mbracket }
      else
        format.html { render :new }
        format.json { render json: @mbracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mbrackets/1
  # PATCH/PUT /mbrackets/1.json
  def update
    respond_to do |format|
      if @mbracket.update(mbracket_params)
        format.html { redirect_to @mbracket, notice: 'Mbracket was successfully updated.' }
        format.json { render :show, status: :ok, location: @mbracket }
      else
        format.html { render :edit }
        format.json { render json: @mbracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mbrackets/1
  # DELETE /mbrackets/1.json
  def destroy
    @mbracket.destroy
    respond_to do |format|
      format.html { redirect_to mbrackets_url, notice: 'Mbracket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mbracket
      @mbracket = Mbracket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mbracket_params
      params.require(:mbracket).permit(:name)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :rank)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mbrackets_helper.rb
module MbracketsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BGolf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mbrackets/_form.html.erb
<%= form_for(@mbracket) do |f| %>
  <% if @mbracket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mbracket.errors.count, "error") %> prohibited this mbracket from being saved:</h2>

      <ul>
      <% @mbracket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mbrackets/edit.html.erb
<h1>Editing Mbracket</h1>

<%= render 'form' %>

<%= link_to 'Show', @mbracket %> |
<%= link_to 'Back', mbrackets_path %>

app/views/mbrackets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mbrackets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mbrackets.each do |mbracket| %>
      <tr>
        <td><%= mbracket.name %></td>
        <td><%= link_to 'Show', mbracket %></td>
        <td><%= link_to 'Edit', edit_mbracket_path(mbracket) %></td>
        <td><%= link_to 'Destroy', mbracket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mbracket', new_mbracket_path %>

app/views/mbrackets/new.html.erb
<h1>New Mbracket</h1>

<%= render 'form' %>


<%= link_to 'Back', mbrackets_path %>

app/views/mbrackets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <center><strong>Name:</strong>
  <%= @mbracket.name %>
</p></center>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="well well-sm">
        <%= @rank1.rank %> &nbsp;<%= @rank1.name %><br><br>
        <%= @rank16.rank %> &nbsp;<%= @rank16.name %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="well well-sm">
        <%= @rank8.rank %> &nbsp;<%= @rank8.name %><br><br>
        <%= @rank9.rank %> &nbsp;<%= @rank9.name %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="well well-sm">
        <%= @rank5.rank %> &nbsp;<%= @rank5.name %><br><br>
        <%= @rank12.rank %> &nbsp;<%= @rank12.name %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="well well-sm">
        <%= @rank4.rank %> &nbsp;<%= @rank4.name %><br><br>
        <%= @rank13.rank %> &nbsp;<%= @rank13.name %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="well well-sm">
        <%= @rank6.rank %> &nbsp;<%= @rank6.name %><br><br>
        <%= @rank11.rank %> &nbsp;<%= @rank11.name %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="well well-sm">
        <%= @rank3.rank %> &nbsp;<%= @rank3.name %><br><br>
        <%= @rank14.rank %> &nbsp;<%= @rank14.name %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="well well-sm">
        <%= @rank7.rank %> &nbsp;<%= @rank7.name %><br><br>
        <%= @rank10.rank %> &nbsp;<%= @rank10.name %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="well well-sm">
        <%= @rank2.rank %> &nbsp;<%= @rank2.name %><br><br>
        <%= @rank15.rank %> &nbsp;<%= @rank15.name %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Edit', edit_mbracket_path(@mbracket) %> |
<%= link_to 'Back', mbrackets_path %>